// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: decoder.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DecoderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EncodeText string `protobuf:"bytes,1,opt,name=encodeText,proto3" json:"encodeText,omitempty"`
}

func (x *DecoderRequest) Reset() {
	*x = DecoderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_decoder_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecoderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecoderRequest) ProtoMessage() {}

func (x *DecoderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_decoder_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecoderRequest.ProtoReflect.Descriptor instead.
func (*DecoderRequest) Descriptor() ([]byte, []int) {
	return file_decoder_proto_rawDescGZIP(), []int{0}
}

func (x *DecoderRequest) GetEncodeText() string {
	if x != nil {
		return x.EncodeText
	}
	return ""
}

type DecoderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DecoderResponse) Reset() {
	*x = DecoderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_decoder_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecoderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecoderResponse) ProtoMessage() {}

func (x *DecoderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_decoder_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecoderResponse.ProtoReflect.Descriptor instead.
func (*DecoderResponse) Descriptor() ([]byte, []int) {
	return file_decoder_proto_rawDescGZIP(), []int{1}
}

func (x *DecoderResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_decoder_proto protoreflect.FileDescriptor

var file_decoder_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x64, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x64, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x22, 0x30, 0x0a, 0x0e, 0x44, 0x65, 0x63, 0x6f,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x6e,
	0x63, 0x6f, 0x64, 0x65, 0x54, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x54, 0x65, 0x78, 0x74, 0x22, 0x25, 0x0a, 0x0f, 0x44, 0x65,
	0x63, 0x6f, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x32, 0x4d, 0x0a, 0x0e, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x06, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x17, 0x2e,
	0x64, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x64, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x72,
	0x2e, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x0f, 0x5a, 0x0d, 0x64, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_decoder_proto_rawDescOnce sync.Once
	file_decoder_proto_rawDescData = file_decoder_proto_rawDesc
)

func file_decoder_proto_rawDescGZIP() []byte {
	file_decoder_proto_rawDescOnce.Do(func() {
		file_decoder_proto_rawDescData = protoimpl.X.CompressGZIP(file_decoder_proto_rawDescData)
	})
	return file_decoder_proto_rawDescData
}

var file_decoder_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_decoder_proto_goTypes = []any{
	(*DecoderRequest)(nil),  // 0: decoder.DecoderRequest
	(*DecoderResponse)(nil), // 1: decoder.DecoderResponse
}
var file_decoder_proto_depIdxs = []int32{
	0, // 0: decoder.DecoderService.Decode:input_type -> decoder.DecoderRequest
	1, // 1: decoder.DecoderService.Decode:output_type -> decoder.DecoderResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_decoder_proto_init() }
func file_decoder_proto_init() {
	if File_decoder_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_decoder_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*DecoderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_decoder_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*DecoderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_decoder_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_decoder_proto_goTypes,
		DependencyIndexes: file_decoder_proto_depIdxs,
		MessageInfos:      file_decoder_proto_msgTypes,
	}.Build()
	File_decoder_proto = out.File
	file_decoder_proto_rawDesc = nil
	file_decoder_proto_goTypes = nil
	file_decoder_proto_depIdxs = nil
}
